# Generated by Django 5.0.3 on 2024-03-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='protagonists',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.FileField(null=True, upload_to='trailers/'),
        ),
    ]
